language: android
env:
  matrix:
    - ANDROID_SDKS=android-19,sysimg-19 ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-21.0.2

    # The SDK version used to compile your project
    - android-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17

# Install gradle 2.1
before_install:
  - sudo rm -r /usr/local/gradle
  - curl -LO http://services.gradle.org/distributions/gradle-2.1-bin.zip
  - unzip -q gradle-2.1-bin.zip
  - sudo mv gradle-2.1 /usr/local/gradle
  
# Emulator Management: Create, Start and Wait
before_script:
  - wget http://services.gradle.org/distributions/gradle-2.1-bin.zip
  - unzip gradle-2.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-2.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  
script: ./gradlew connectedAndroidTest
